import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'
import { useEffect } from 'react'

type Props = {
  children: JSX.Element | JSX.Element[]
  location: string
  title: string
}

export default function Layout({ children, location, title }: Props) {
  useEffect(() => {
    document.title = `${title} | ${process.env.REACT_APP_SITE_TITLE || 'Pobre TV Scraper'}`
  }, [title])

  return (
    <div id="layout" className="layout">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header location={location} siteTitle="Pobre TV Scraper" />
      <div className="my-auto">{children}</div>
      <Footer />
    </div>
  )
}
